@startuml
participant TransactionInterceptor as A
participant TransactionAspectSupport as B
participant AbstractPlatformTransactionManager as C
participant DataSourceTransactionManager as D

autonumber
A -> B ++ : invokeWithinTransaction\n(Method,Class,InvocationCallback)
    B -> B ++ : commitTransactionAfterReturning(TransactionInfo)
        B -> C ++ : commit(TransactionStatus);
            C -> C ++ : processCommit(DefaultTransactionStatus)
                C -> C : prepareForCommit(DefaultTransactionStatus)
                C -> C : triggerBeforeCommit(DefaultTransactionStatus)
                C -> C : triggerBeforeCompletion(DefaultTransactionStatus)

                C -> D ++ : doCommit(DefaultTransactionStatus)

                return
                C -> C : triggerAfterCommit(DefaultTransactionStatus)
                C -> C : triggerAfterCompletion(DefaultTransactionStatus, int completionStatus)
                C -> C : cleanupAfterCompletion(DefaultTransactionStatus)
            return
        return
    return
return
@enduml